import avatar1 from "@/public/images/avatar/avatar-1.jpg";
import avatar2 from "@/public/images/avatar/avatar-2.jpg";
import avatar3 from "@/public/images/avatar/avatar-3.jpg";
import avatar4 from "@/public/images/avatar/avatar-4.jpg";
import avatar5 from "@/public/images/avatar/avatar-5.jpg";
import avatar6 from "@/public/images/avatar/avatar-6.jpg";
import avatar7 from "@/public/images/avatar/avatar-7.jpg";

export const usuarios = [
  {
    id: "USR-001",
    name: "Dashtail Admin",
    email: "dashtail@codeshaper.net",
    password: "password",
    image: avatar3,
    role: "admin",
    status: "active",
    phone: "+1 234 567 8900",
    department: "IT",
    position: "System Administrator",
    createdAt: "2024-01-15",
    resetToken: null,
    resetTokenExpiry: null,
  },
  {
    id: "USR-002",
    name: "María González",
    email: "maria.gonzalez@company.com",
    password: "password123",
    image: avatar1,
    role: "user",
    status: "active",
    phone: "+1 234 567 8901",
    department: "Ventas",
    position: "Gerente de Ventas",
    createdAt: "2024-02-10",
    resetToken: null,
    resetTokenExpiry: null,
  },
  {
    id: "USR-003",
    name: "Carlos Rodríguez",
    email: "carlos.rodriguez@company.com",
    password: "password123",
    image: avatar2,
    role: "user",
    status: "active",
    phone: "+1 234 567 8902",
    department: "Marketing",
    position: "Especialista de Marketing",
    createdAt: "2024-02-15",
    resetToken: null,
    resetTokenExpiry: null,
  },
  {
    id: "USR-004",
    name: "Ana López",
    email: "ana.lopez@company.com",
    password: "password123",
    image: avatar4,
    role: "manager",
    status: "active",
    phone: "+1 234 567 8903",
    department: "Recursos Humanos",
    position: "Directora de RRHH",
    createdAt: "2024-03-01",
    resetToken: null,
    resetTokenExpiry: null,
  },
  {
    id: "USR-005",
    name: "Juan Pérez",
    email: "juan.perez@company.com",
    password: "password123",
    image: avatar5,
    role: "user",
    status: "inactive",
    phone: "+1 234 567 8904",
    department: "Operaciones",
    position: "Coordinador",
    createdAt: "2024-03-10",
    resetToken: null,
    resetTokenExpiry: null,
  },
  {
    id: "USR-006",
    name: "Laura Martínez",
    email: "laura.martinez@company.com",
    password: "password123",
    image: avatar6,
    role: "user",
    status: "active",
    phone: "+1 234 567 8905",
    department: "Finanzas",
    position: "Analista Financiero",
    createdAt: "2024-03-20",
    resetToken: null,
    resetTokenExpiry: null,
  },
  {
    id: "USR-007",
    name: "Roberto Sánchez",
    email: "roberto.sanchez@company.com",
    password: "password123",
    image: avatar7,
    role: "manager",
    status: "active",
    phone: "+1 234 567 8906",
    department: "IT",
    position: "Gerente de TI",
    createdAt: "2024-04-01",
    resetToken: null,
    resetTokenExpiry: null,
  },
  {
    id: "USR-008",
    name: "Patricia Díaz",
    email: "patricia.diaz@company.com",
    password: "password123",
    image: avatar1,
    role: "user",
    status: "pending",
    phone: "+1 234 567 8907",
    department: "Ventas",
    position: "Representante de Ventas",
    createdAt: "2024-04-10",
    resetToken: null,
    resetTokenExpiry: null,
  },
  {
    id: "USR-009",
    name: "Miguel Torres",
    email: "miguel.torres@company.com",
    password: "password123",
    image: avatar2,
    role: "user",
    status: "active",
    phone: "+1 234 567 8908",
    department: "Soporte",
    position: "Técnico de Soporte",
    createdAt: "2024-04-15",
    resetToken: null,
    resetTokenExpiry: null,
  },
  {
    id: "USR-010",
    name: "Sofia Ramírez",
    email: "sofia.ramirez@company.com",
    password: "password123",
    image: avatar4,
    role: "user",
    status: "active",
    phone: "+1 234 567 8909",
    department: "Marketing",
    position: "Diseñadora Gráfica",
    createdAt: "2024-05-01",
    resetToken: null,
    resetTokenExpiry: null,
  },
];

