export const transacciones = [
  {
    id: "TRX-001",
    fecha: "2024-10-15",
    tipo: "ingreso",
    categoria: "Ventas",
    subcategoria: "Productos",
    monto: 5000.00,
    metodoPago: "transferencia",
    cuenta: "Banco Principal",
    descripcion: "Venta de productos - Cliente Premium SA",
    referencia: "INV-2024-001",
    estado: "completado",
    comprobante: "COMP-001.pdf",
    createdBy: "USR-001",
    createdAt: "2024-10-15T10:30:00",
  },
  {
    id: "TRX-002",
    fecha: "2024-10-14",
    tipo: "egreso",
    categoria: "Gastos Operativos",
    subcategoria: "Servicios",
    monto: 1200.00,
    metodoPago: "efectivo",
    cuenta: "Caja Chica",
    descripcion: "Pago de servicios públicos - Octubre",
    referencia: "BILL-2024-089",
    estado: "completado",
    comprobante: null,
    createdBy: "USR-001",
    createdAt: "2024-10-14T14:20:00",
  },
  {
    id: "TRX-003",
    fecha: "2024-10-13",
    tipo: "ingreso",
    categoria: "Servicios",
    subcategoria: "Consultoría",
    monto: 3500.00,
    metodoPago: "cheque",
    cuenta: "Banco Principal",
    descripcion: "Servicio de consultoría - Proyecto Alpha",
    referencia: "CONS-2024-015",
    estado: "pendiente",
    comprobante: null,
    createdBy: "USR-002",
    createdAt: "2024-10-13T09:15:00",
  },
  {
    id: "TRX-004",
    fecha: "2024-10-12",
    tipo: "egreso",
    categoria: "Nómina",
    subcategoria: "Salarios",
    monto: 25000.00,
    metodoPago: "transferencia",
    cuenta: "Banco Principal",
    descripcion: "Pago de nómina quincenal",
    referencia: "NOM-2024-10-Q1",
    estado: "completado",
    comprobante: "NOM-001.pdf",
    createdBy: "USR-001",
    createdAt: "2024-10-12T16:00:00",
  },
  {
    id: "TRX-005",
    fecha: "2024-10-11",
    tipo: "ingreso",
    categoria: "Ventas",
    subcategoria: "Servicios",
    monto: 8500.00,
    metodoPago: "transferencia",
    cuenta: "Banco Principal",
    descripcion: "Contrato de mantenimiento mensual",
    referencia: "MANT-2024-098",
    estado: "completado",
    comprobante: "COMP-005.pdf",
    createdBy: "USR-003",
    createdAt: "2024-10-11T11:45:00",
  },
  {
    id: "TRX-006",
    fecha: "2024-10-10",
    tipo: "egreso",
    categoria: "Marketing",
    subcategoria: "Publicidad",
    monto: 2800.00,
    metodoPago: "tarjeta",
    cuenta: "Tarjeta Corporativa",
    descripcion: "Campaña publicitaria en redes sociales",
    referencia: "MKT-2024-045",
    estado: "completado",
    comprobante: "MKT-045.pdf",
    createdBy: "USR-004",
    createdAt: "2024-10-10T13:30:00",
  },
  {
    id: "TRX-007",
    fecha: "2024-10-09",
    tipo: "egreso",
    categoria: "Compras",
    subcategoria: "Inventario",
    monto: 15000.00,
    metodoPago: "transferencia",
    cuenta: "Banco Principal",
    descripcion: "Compra de materia prima - Proveedor XYZ",
    referencia: "PO-2024-122",
    estado: "completado",
    comprobante: "PO-122.pdf",
    createdBy: "USR-002",
    createdAt: "2024-10-09T10:00:00",
  },
  {
    id: "TRX-008",
    fecha: "2024-10-08",
    tipo: "ingreso",
    categoria: "Ventas",
    subcategoria: "Productos",
    monto: 6200.00,
    metodoPago: "efectivo",
    cuenta: "Caja General",
    descripcion: "Venta al contado - Cliente varios",
    referencia: "VENTA-2024-345",
    estado: "completado",
    comprobante: null,
    createdBy: "USR-005",
    createdAt: "2024-10-08T15:20:00",
  },
  {
    id: "TRX-009",
    fecha: "2024-10-07",
    tipo: "egreso",
    categoria: "Gastos Administrativos",
    subcategoria: "Suministros",
    monto: 850.00,
    metodoPago: "efectivo",
    cuenta: "Caja Chica",
    descripcion: "Compra de suministros de oficina",
    referencia: "SUPP-2024-078",
    estado: "completado",
    comprobante: null,
    createdBy: "USR-001",
    createdAt: "2024-10-07T09:45:00",
  },
  {
    id: "TRX-010",
    fecha: "2024-10-06",
    tipo: "ingreso",
    categoria: "Otros Ingresos",
    subcategoria: "Intereses",
    monto: 450.00,
    metodoPago: "transferencia",
    cuenta: "Banco Principal",
    descripcion: "Intereses bancarios del mes",
    referencia: "INT-2024-10",
    estado: "completado",
    comprobante: "INT-10.pdf",
    createdBy: "USR-001",
    createdAt: "2024-10-06T08:00:00",
  },
  {
    id: "TRX-011",
    fecha: "2024-10-05",
    tipo: "egreso",
    categoria: "Tecnología",
    subcategoria: "Software",
    monto: 3200.00,
    metodoPago: "tarjeta",
    cuenta: "Tarjeta Corporativa",
    descripcion: "Renovación de licencias de software",
    referencia: "LIC-2024-033",
    estado: "pendiente",
    comprobante: null,
    createdBy: "USR-002",
    createdAt: "2024-10-05T12:00:00",
  },
  {
    id: "TRX-012",
    fecha: "2024-10-04",
    tipo: "ingreso",
    categoria: "Servicios",
    subcategoria: "Capacitación",
    monto: 4500.00,
    metodoPago: "transferencia",
    cuenta: "Banco Principal",
    descripcion: "Curso de capacitación empresarial",
    referencia: "CAP-2024-019",
    estado: "completado",
    comprobante: "CAP-019.pdf",
    createdBy: "USR-003",
    createdAt: "2024-10-04T14:30:00",
  },
];

export const cuentas = [
  {
    id: "CTA-001",
    nombre: "Banco Principal",
    tipo: "banco",
    numeroCuenta: "****1234",
    banco: "Banco Nacional",
    saldo: 125000.00,
    moneda: "USD",
    estado: "activo",
    descripcion: "Cuenta principal de operaciones",
  },
  {
    id: "CTA-002",
    nombre: "Caja General",
    tipo: "efectivo",
    numeroCuenta: null,
    banco: null,
    saldo: 8500.00,
    moneda: "USD",
    estado: "activo",
    descripcion: "Caja general para ventas al contado",
  },
  {
    id: "CTA-003",
    nombre: "Caja Chica",
    tipo: "efectivo",
    numeroCuenta: null,
    banco: null,
    saldo: 2000.00,
    moneda: "USD",
    estado: "activo",
    descripcion: "Fondo fijo para gastos menores",
  },
  {
    id: "CTA-004",
    nombre: "Tarjeta Corporativa",
    tipo: "tarjeta",
    numeroCuenta: "****5678",
    banco: "Banco Nacional",
    saldo: -6000.00,
    moneda: "USD",
    estado: "activo",
    descripcion: "Tarjeta de crédito corporativa",
  },
  {
    id: "CTA-005",
    nombre: "Banco Secundario",
    tipo: "banco",
    numeroCuenta: "****9012",
    banco: "Banco Internacional",
    saldo: 45000.00,
    moneda: "USD",
    estado: "activo",
    descripcion: "Cuenta de respaldo",
  },
];

export const categorias = [
  // Ingresos
  { id: "CAT-001", nombre: "Ventas", tipo: "ingreso", descripcion: "Ingresos por ventas de productos y servicios", icono: "ShoppingCart", color: "green" },
  { id: "CAT-002", nombre: "Servicios", tipo: "ingreso", descripcion: "Ingresos por servicios prestados", icono: "Briefcase", color: "blue" },
  { id: "CAT-003", nombre: "Otros Ingresos", tipo: "ingreso", descripcion: "Ingresos varios", icono: "Plus", color: "teal" },
  
  // Egresos
  { id: "CAT-004", nombre: "Nómina", tipo: "egreso", descripcion: "Pagos de salarios y beneficios", icono: "Users", color: "red" },
  { id: "CAT-005", nombre: "Gastos Operativos", tipo: "egreso", descripcion: "Gastos de operación diaria", icono: "Settings", color: "orange" },
  { id: "CAT-006", nombre: "Marketing", tipo: "egreso", descripcion: "Gastos de marketing y publicidad", icono: "Megaphone", color: "purple" },
  { id: "CAT-007", nombre: "Compras", tipo: "egreso", descripcion: "Compra de inventario y materia prima", icono: "Package", color: "yellow" },
  { id: "CAT-008", nombre: "Gastos Administrativos", tipo: "egreso", descripcion: "Gastos administrativos generales", icono: "FileText", color: "gray" },
  { id: "CAT-009", nombre: "Tecnología", tipo: "egreso", descripcion: "Inversión en tecnología", icono: "Laptop", color: "indigo" },
];

